# Generated by Django 4.2.3 on 2023-08-04 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_article_category_alter_article_created_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="category",),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 8, 4, 16, 39, 13, 663465)
            ),
        ),
    ]
