# Generated by Django 4.2.3 on 2023-08-04 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_article_category_alter_article_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 8, 4, 16, 43, 5, 40907)
            ),
        ),
    ]
